---
- hosts: all
  become: yes
  tasks:
  - name: installing httpd on redhat
    yum: 
      name: httpd
      state: present
      when: ansible_os_family == "RedHat"       
  - name: installing apache2 on ubuntu
    apt:
      name: apache2
      state: present
      when: ansible_os_family == "Debian"
